In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
print(a[0,:])

[1 2 3]


In [11]:
print(a[0])
print(a[1])
print(a[1,:])


[1 2 3]
[4 5 6]
[4 5 6]


In [13]:
print(a[:,0])
print(a[:,1])
print(a[:,2])

[1 4]
[2 5]
[3 6]


In [24]:
b= np.array([[7, 8, 9], [10, 11, 12]])
print(b[:,[0, 2]])
test = np.arange(9).reshape((3, 3))
test
test[:,[1, 2]]

[[ 7  9]
 [10 12]]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [26]:
a = np.array([[1, 2, 3],
           [4, 5, 6]])

In [27]:
# The zeroth item along the first axis is:
a[0,:]
a[0]
# the first axis is rows

array([1, 2, 3])

In [30]:
# The zeroth item along the second axis is:
print(a[:, 0]) # col 1
a[:,[1, 2]] # col 2, 3
# the second axis is columns

[1 4]


array([[2, 3],
       [5, 6]])

In [32]:
b = np.array([[7, 8, 9],
           [10, 11, 12]])


In [35]:
#  can concatenate them along the first axis (x_axis)
print(np.r_[a, b])
print(np.r_[a, b][:, [0, 2]])
#  stack them on top of each other

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


In [36]:
#  concatenate along the second axis (y_axis)
print(np.c_[a, b])
# So, put them next to each other

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [40]:
"""
It's useful, as it says in the documentation, to build up arrays - 
for example if you had a `for` loop or something that builds up an array column by column, 
the `c_` helper will be useful. Ditto if you build it up row by row, with `r_`.
"""
print(__doc__)


It's useful, as it says in the documentation, to build up arrays - 
for example if you had a `for` loop or something that builds up an array column by column, 
the `c_` helper will be useful. Ditto if you build it up row by row, with `r_`.

